name: Deploy Next.js App

on:
  push:
      branches:
        - main # triggers workfow on push to the 'main' branch 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1 Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2 Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21
        cache: npm

    # Step 3 Install Dependencies
    - name: Install Dependencies
      run: npm install

    # Step 4 Build the project
    - name: Build Next.js App
      run: npm run build

    # Debug SSH key
    - name: Debug SSH Key
      run: |
          echo "${{ secrets.VPS_PRIVATE_KEY }}" | base64 -d
    # Test SSH Connection
    - name: Test SSH Connection
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 5522 user@your-vps-ip "echo Connected"

    # Step 5 Test connextion to VPS
    - name: Test SSH connection to VPS
      run: |
        nc -zv ${{ secrets.VPS_HOST }} 5522

    # Step 5 Deploy to VPS using SSH
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}  # Ensure this is the correct private key in GitHub Secrets
        port: 5522
        script: |
          cd /home/norbu/projects/gurukulStudio
          git pull origin main
          npm install
          npm run build
          pm2 restart nextjs-app
